spring:
  flyway:
    enabled: true
    locations: classpath:db/migration/{vendor}
    out-of-order: true
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
    hibernate:
      ddl-auto: validate
