server:
  port: 38088

spring:
  application:
    name: uc-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/apzda_uc_db?characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: Abc12332!
  data:
    redis:
      database: 1
      lettuce:
        pool:
          enabled: true
  flyway:
    enabled: false
  jpa:
    open-in-view: false
  config:
    import: classpath:apzda.uc.service.properties
logging:
  level:
    com.apzda.cloud: trace
