spring:
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

apzda:
  ucenter:
    server:
      endpoint:
        username-password: /ucenter/login
        switch-to: /ucenter/switch-to
        switch-back: /ucenter/switch-back
        refresh-token: /ucenter/refresh-token
      authenticator: com.apzda.cloud.uc.security.mfa.GoogleTotpAuthenticator
    security:
      resources:
        user:
          name: User
          explorer: com.apzda.cloud.uc.resource.UserIdExplorer
          privileges:
            "[*:user.*]":
              name: UserFullAccess
              type: resource
              description: 管理系统账户的权限
            "[r:user.*]":
              name: UserReadOnlyAccess
              type: resource
              description: 只读访问系统账户的权限
        role:
          name: Role
          privileges:
            "[*:role.*]":
              name: RoleFullAccess
              type: resource
              description: 管理系统角色的权限
            "[r:role.*]":
              name: RoleReadOnlyAccess
              type: resource
              description: 只读访问系统角色的权限
        privilege:
          name: Privilege
          privileges:
            "[*:privilege.*]":
              name: PrivilegeFullAccess
              type: resource
              description: 管理系统权限的权限
            "[r:privilege.*]":
              name: PrivilegeReadOnlyAccess
              type: resource
              description: 只读访问系统权限的权限
          children:
            resource:
              name: Resource
              description: 系统里可被访问的资源
              actions: r
      privileges:
        "[*:*]":
          name: All Privileges
          description: 超级权限
          type: resource
        RUNAS:
          name: Run As
          description: 变身普通用户，代替普通用户操作.
          type: authority
        SIMPLE_USER:
          name: Simple User
          type: authority
          description: 普通用户
      roles:
        sa:
          name: Super Administrator
          description: 超级管理员
        admin:
          name: Administrator
          description: 管理员
        user:
          name: Authenticated User
          description: 普通用户
