server:
  port: 30902

spring:
  application:
    name: ucenter-service
  config:
    import: classpath:/druid.properties
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: ENC(etZ5PVB40lymY0rIeRK3Q0tSdW3Ftjdsx2IBkEPx/4qxu2Lnzgkywl4Z89nN86Fc)
    url: jdbc:mysql://${spring.datasource.host}:3306/apzda_uc_db?characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ENC(amxsb/5GE92W7SmwbvRLQCN8GGnnwe1ZgMMM7UvbBC8N1uz31oMiWe/O9qWEDwLX)
    password: ENC(ft2+PBi1ZCeIoD6gpiOHgmTf+AX4VmuqjUXQz1iyflzVQehpQmSGXR0rXw6hby1c)
    druid:
      initial-size: 5

  flyway:
    enabled: false
  data:
    redis:
      database: 1
      lettuce:
        pool:
          enabled: true

logging:
  level:
    com.apzda.cloud: debug
    web: info

apzda:
  ucenter:
    server:
      endpoint:
        username-password: /uc/login

  cloud:
    reference:
      CaptchaService:
        svc-name: http://localhost:38082
