apzda:
  cloud:
    registry:
      type: docker
      name-style: dashed
    security:
      meta-repo: redis

logging:
  level:
    com.apzda.cloud: debug
  pattern:
    console: "%d{\"yyyy-MM-dd'T'HH:mm:ss.SSSXXX\"} [%thread] %level %logger{64}:%L - %X{tid} - %msg%n"
