server:
  port: 30902

spring:
  application:
    name: ucenter-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/apzda_uc_db?characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: Abc12332!
    druid:
      initial-size: 5

  flyway:
    enabled: false
  data:
    redis:
      database: 1
      lettuce:
        pool:
          enabled: true

logging:
  level:
    com.apzda.cloud: debug
    web: info

apzda:
  ucenter:
    server:
      endpoint:
        username-password: /uc/login

  cloud:
    reference:
      CaptchaService:
        svc-name: http://localhost:38082
