server:
  port: 30902

spring:
  application:
    name: ucenter-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/apzda_uc_db?characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: Abc12332!
  jpa:
    show-sql: true

logging:
  level:
    com.apzda.cloud: trace
    web: info
