apzda:
  cloud:
    registry:
      type: docker
      name-style: dashed
    security:
      meta-repo: redis

logging:
  level:
    com.apzda.cloud: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSSXXX} %-5level --- [%15.15t] %-40.40logger{39}:%-4L -%X{tid}- %msg%n"
